source 'https://rubygems.org'

group :jekyll_plugins do
  gem 'webrick'
  gem 'github-pages'
  #gem 'minima'
  #gem 'kramdown'
  #gem 'liquid'
  #gem 'rouge'
  #gem 'github-pages-health-check'
  #gem 'jemoji'
  #gem 'jekyll-mentions'
  #gem 'jekyll-redirect-from'
  #gem 'jekyll-sitemap'
  #gem 'jekyll-feed'
  #gem 'jekyll-gist'
  gem 'jekyll-paginate'
  #gem 'jekyll-coffeescript'
  #gem 'jekyll-seo-tag'
  #gem 'jekyll-github-metadata'
  #gem 'listen'
  #gem 'activesupport'
  gem 'jekyll-datapage-generator'
end

gem 'html-proofer'
gem 'jekyll-tidy'
