name: updateSharedBlockAutomation

on:
  push:
    branches-ignore:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # 원하는 Node.js 버전으로 변경

      - name: Install Dependencies
        run: npm install

      - name: Run updateSharedBlockTag
        run: node .github/updateSharedBlockTag.js

      - name: Run updateSharedBlockBlock
        run: node .github/updateSharedBlockBlock.js
        
      # .github/updateSortedData.js
      - name: Run updateAlgorithmAndDataStruct
        run: node .github/updateSortedData.js

      # comit and push
      - name: Commit and Push Changes
        run:
          git config --local user.name actions-user
          
          git config --local user.email "actions@github.com"

          git add .

          git commit -m "Update updateSharedBlockAutomation"

          git push
